[ 2025-02-10 21:01:56,423 ] 23 root - INFO - Initialized Data Ingestion with config: <customer_churn.entity.config_entity.DataIngestionConfig object at 0x0000019CCD1B3230>
[ 2025-02-10 21:01:56,423 ] 18 root - INFO - Initiate the data ingestion
[ 2025-02-10 21:01:56,423 ] 107 root - INFO - Starting data ingestion process...
[ 2025-02-10 21:01:56,423 ] 109 root - INFO - Fetching data from MongoDB...
[ 2025-02-10 21:01:56,423 ] 32 root - INFO - Connecting to MongoDB...
[ 2025-02-10 21:01:56,920 ] 38 root - INFO - Fetching data from MongoDB: Database = UDAYML, Collection = CustomerChurn
[ 2025-02-10 21:01:59,739 ] 45 root - INFO - Dropping '_id' column from DataFrame
[ 2025-02-10 21:01:59,756 ] 47 root - INFO - Exported 7043 rows from MongoDB successfully.
[ 2025-02-10 21:01:59,765 ] 112 root - INFO - Saving raw data to feature store...
[ 2025-02-10 21:01:59,767 ] 62 root - INFO - Creating feature store directory: Artifacts\02_10_2025_21_01_46\data_ingestion\feature_store\Telecome_Churn_Data
[ 2025-02-10 21:01:59,767 ] 65 root - INFO - Saving raw data to feature store at: Artifacts\02_10_2025_21_01_46\data_ingestion\feature_store\Telecome_Churn_Data/WA_Fn-UseC_-Telco-Customer-Churn.csv
[ 2025-02-10 21:01:59,767 ] 128 root - ERROR - Error occurred during data ingestion: Error occurred in [D:\MLops\Custer Churn Prediction System\customer_churn\Components\data_ingestion.py] at line [66] - Message: 'NoneType' object has no attribute 'to_csv'
